repos:
- repo: local
  hooks:
  - id: format
    name: Format
    entry: bazelisk run //tools/format:format
    language: system
    pass_filenames: false
    types: [text]
  - id: lint
    name: Lint
    entry: bazelisk lint :all
    language: system
    pass_filenames: false
    types: [text]
  - id: mypy
    name: mypy
    entry: bazelisk run //:mypy
    language: system
    pass_filenames: false
    types: [text]
